# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fastMean <- function(xx) {
    .Call(`_BayesESS_fastMean`, xx)
}

fastProd <- function(X, Y) {
    .Call(`_BayesESS_fastProd`, X, Y)
}

fastSum <- function(xx) {
    .Call(`_BayesESS_fastSum`, xx)
}

