// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// prior_nonc_t
double prior_nonc_t(const double a1, const double p1, const double sigma1, const double nu, const double lam1);
RcppExport SEXP _BHSBVAR_prior_nonc_t(SEXP a1SEXP, SEXP p1SEXP, SEXP sigma1SEXP, SEXP nuSEXP, SEXP lam1SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double >::type a1(a1SEXP);
    Rcpp::traits::input_parameter< const double >::type p1(p1SEXP);
    Rcpp::traits::input_parameter< const double >::type sigma1(sigma1SEXP);
    Rcpp::traits::input_parameter< const double >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< const double >::type lam1(lam1SEXP);
    rcpp_result_gen = Rcpp::wrap(prior_nonc_t(a1, p1, sigma1, nu, lam1));
    return rcpp_result_gen;
END_RCPP
}
// prior_t_n
double prior_t_n(const double a1, const double p1, const double sigma1, const double nu);
RcppExport SEXP _BHSBVAR_prior_t_n(SEXP a1SEXP, SEXP p1SEXP, SEXP sigma1SEXP, SEXP nuSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double >::type a1(a1SEXP);
    Rcpp::traits::input_parameter< const double >::type p1(p1SEXP);
    Rcpp::traits::input_parameter< const double >::type sigma1(sigma1SEXP);
    Rcpp::traits::input_parameter< const double >::type nu(nuSEXP);
    rcpp_result_gen = Rcpp::wrap(prior_t_n(a1, p1, sigma1, nu));
    return rcpp_result_gen;
END_RCPP
}
// prior_t_p
double prior_t_p(const double a1, const double p1, const double sigma1, const double nu);
RcppExport SEXP _BHSBVAR_prior_t_p(SEXP a1SEXP, SEXP p1SEXP, SEXP sigma1SEXP, SEXP nuSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double >::type a1(a1SEXP);
    Rcpp::traits::input_parameter< const double >::type p1(p1SEXP);
    Rcpp::traits::input_parameter< const double >::type sigma1(sigma1SEXP);
    Rcpp::traits::input_parameter< const double >::type nu(nuSEXP);
    rcpp_result_gen = Rcpp::wrap(prior_t_p(a1, p1, sigma1, nu));
    return rcpp_result_gen;
END_RCPP
}
// prior_t
double prior_t(const double a1, const double p1, const double sigma1, const double nu);
RcppExport SEXP _BHSBVAR_prior_t(SEXP a1SEXP, SEXP p1SEXP, SEXP sigma1SEXP, SEXP nuSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double >::type a1(a1SEXP);
    Rcpp::traits::input_parameter< const double >::type p1(p1SEXP);
    Rcpp::traits::input_parameter< const double >::type sigma1(sigma1SEXP);
    Rcpp::traits::input_parameter< const double >::type nu(nuSEXP);
    rcpp_result_gen = Rcpp::wrap(prior_t(a1, p1, sigma1, nu));
    return rcpp_result_gen;
END_RCPP
}
// prior_beta
double prior_beta(const double a1, const double sh1, const double sh2);
RcppExport SEXP _BHSBVAR_prior_beta(SEXP a1SEXP, SEXP sh1SEXP, SEXP sh2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double >::type a1(a1SEXP);
    Rcpp::traits::input_parameter< const double >::type sh1(sh1SEXP);
    Rcpp::traits::input_parameter< const double >::type sh2(sh2SEXP);
    rcpp_result_gen = Rcpp::wrap(prior_beta(a1, sh1, sh2));
    return rcpp_result_gen;
END_RCPP
}
// prior_ibeta
double prior_ibeta(const double a1, const double sh1, const double sh2);
RcppExport SEXP _BHSBVAR_prior_ibeta(SEXP a1SEXP, SEXP sh1SEXP, SEXP sh2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double >::type a1(a1SEXP);
    Rcpp::traits::input_parameter< const double >::type sh1(sh1SEXP);
    Rcpp::traits::input_parameter< const double >::type sh2(sh2SEXP);
    rcpp_result_gen = Rcpp::wrap(prior_ibeta(a1, sh1, sh2));
    return rcpp_result_gen;
END_RCPP
}
// sum_log_prior_densities
double sum_log_prior_densities(const arma::mat& A_test, const arma::cube& pA, const arma::cube& pdetA, const arma::cube& pH);
RcppExport SEXP _BHSBVAR_sum_log_prior_densities(SEXP A_testSEXP, SEXP pASEXP, SEXP pdetASEXP, SEXP pHSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type A_test(A_testSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type pA(pASEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type pdetA(pdetASEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type pH(pHSEXP);
    rcpp_result_gen = Rcpp::wrap(sum_log_prior_densities(A_test, pA, pdetA, pH));
    return rcpp_result_gen;
END_RCPP
}
// log_likelihood_function
double log_likelihood_function(const arma::mat& A_test, const arma::mat& kappa1, const arma::mat& y1, const arma::mat& omega, const arma::mat& zeta_test, const arma::mat& somega);
RcppExport SEXP _BHSBVAR_log_likelihood_function(SEXP A_testSEXP, SEXP kappa1SEXP, SEXP y1SEXP, SEXP omegaSEXP, SEXP zeta_testSEXP, SEXP somegaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type A_test(A_testSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type kappa1(kappa1SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type y1(y1SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type omega(omegaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type zeta_test(zeta_testSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type somega(somegaSEXP);
    rcpp_result_gen = Rcpp::wrap(log_likelihood_function(A_test, kappa1, y1, omega, zeta_test, somega));
    return rcpp_result_gen;
END_RCPP
}
// MAIN
Rcpp::List MAIN(const arma::mat& y1, const arma::mat& x1, const arma::mat& omega, const arma::mat& somega, const arma::uword nlags, const arma::cube& pA, const arma::cube& pdetA, const arma::cube& pH, const arma::mat& pP, const arma::mat& pP_sig, const arma::cube& pR_sig, const arma::mat& kappa1, const arma::mat& A_start, const arma::uword itr, const arma::uword burn, const arma::uword thin, const arma::mat& scale1, const arma::uword h1_irf, const bool acc_irf, const double ci, const Rcpp::StringVector& varnames, const Rcpp::Function& line_plot, const Rcpp::Function& acf_plot, const bool& rA, const bool& rB, const bool& rD);
RcppExport SEXP _BHSBVAR_MAIN(SEXP y1SEXP, SEXP x1SEXP, SEXP omegaSEXP, SEXP somegaSEXP, SEXP nlagsSEXP, SEXP pASEXP, SEXP pdetASEXP, SEXP pHSEXP, SEXP pPSEXP, SEXP pP_sigSEXP, SEXP pR_sigSEXP, SEXP kappa1SEXP, SEXP A_startSEXP, SEXP itrSEXP, SEXP burnSEXP, SEXP thinSEXP, SEXP scale1SEXP, SEXP h1_irfSEXP, SEXP acc_irfSEXP, SEXP ciSEXP, SEXP varnamesSEXP, SEXP line_plotSEXP, SEXP acf_plotSEXP, SEXP rASEXP, SEXP rBSEXP, SEXP rDSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type y1(y1SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type x1(x1SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type omega(omegaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type somega(somegaSEXP);
    Rcpp::traits::input_parameter< const arma::uword >::type nlags(nlagsSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type pA(pASEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type pdetA(pdetASEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type pH(pHSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type pP(pPSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type pP_sig(pP_sigSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type pR_sig(pR_sigSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type kappa1(kappa1SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type A_start(A_startSEXP);
    Rcpp::traits::input_parameter< const arma::uword >::type itr(itrSEXP);
    Rcpp::traits::input_parameter< const arma::uword >::type burn(burnSEXP);
    Rcpp::traits::input_parameter< const arma::uword >::type thin(thinSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type scale1(scale1SEXP);
    Rcpp::traits::input_parameter< const arma::uword >::type h1_irf(h1_irfSEXP);
    Rcpp::traits::input_parameter< const bool >::type acc_irf(acc_irfSEXP);
    Rcpp::traits::input_parameter< const double >::type ci(ciSEXP);
    Rcpp::traits::input_parameter< const Rcpp::StringVector& >::type varnames(varnamesSEXP);
    Rcpp::traits::input_parameter< const Rcpp::Function& >::type line_plot(line_plotSEXP);
    Rcpp::traits::input_parameter< const Rcpp::Function& >::type acf_plot(acf_plotSEXP);
    Rcpp::traits::input_parameter< const bool& >::type rA(rASEXP);
    Rcpp::traits::input_parameter< const bool& >::type rB(rBSEXP);
    Rcpp::traits::input_parameter< const bool& >::type rD(rDSEXP);
    rcpp_result_gen = Rcpp::wrap(MAIN(y1, x1, omega, somega, nlags, pA, pdetA, pH, pP, pP_sig, pR_sig, kappa1, A_start, itr, burn, thin, scale1, h1_irf, acc_irf, ci, varnames, line_plot, acf_plot, rA, rB, rD));
    return rcpp_result_gen;
END_RCPP
}
