# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @useDynLib BHSBVAR, .registration = TRUE
#' @keywords internal
prior_nonc_t <- function(a1, p1, sigma1, nu, lam1) {
    .Call(`_BHSBVAR_prior_nonc_t`, a1, p1, sigma1, nu, lam1)
}

#' @useDynLib BHSBVAR, .registration = TRUE
#' @keywords internal
prior_t_n <- function(a1, p1, sigma1, nu) {
    .Call(`_BHSBVAR_prior_t_n`, a1, p1, sigma1, nu)
}

#' @useDynLib BHSBVAR, .registration = TRUE
#' @keywords internal
prior_t_p <- function(a1, p1, sigma1, nu) {
    .Call(`_BHSBVAR_prior_t_p`, a1, p1, sigma1, nu)
}

#' @useDynLib BHSBVAR, .registration = TRUE
#' @keywords internal
prior_t <- function(a1, p1, sigma1, nu) {
    .Call(`_BHSBVAR_prior_t`, a1, p1, sigma1, nu)
}

#' @useDynLib BHSBVAR, .registration = TRUE
#' @keywords internal
prior_beta <- function(a1, sh1, sh2) {
    .Call(`_BHSBVAR_prior_beta`, a1, sh1, sh2)
}

#' @useDynLib BHSBVAR, .registration = TRUE
#' @keywords internal
prior_ibeta <- function(a1, sh1, sh2) {
    .Call(`_BHSBVAR_prior_ibeta`, a1, sh1, sh2)
}

#' @useDynLib BHSBVAR, .registration = TRUE
#' @keywords internal
sum_log_prior_densities <- function(A_test, pA, pdetA, pH) {
    .Call(`_BHSBVAR_sum_log_prior_densities`, A_test, pA, pdetA, pH)
}

#' @useDynLib BHSBVAR, .registration = TRUE
#' @keywords internal
log_likelihood_function <- function(A_test, kappa1, y1, omega, zeta_test, somega) {
    .Call(`_BHSBVAR_log_likelihood_function`, A_test, kappa1, y1, omega, zeta_test, somega)
}

#' @useDynLib BHSBVAR, .registration = TRUE
#' @keywords internal
MAIN <- function(y1, x1, omega, somega, nlags, pA, pdetA, pH, pP, pP_sig, pR_sig, kappa1, A_start, itr, burn, thin, scale1, h1_irf, acc_irf, ci, varnames, line_plot, acf_plot, rA, rB, rD) {
    .Call(`_BHSBVAR_MAIN`, y1, x1, omega, somega, nlags, pA, pdetA, pH, pP, pP_sig, pR_sig, kappa1, A_start, itr, burn, thin, scale1, h1_irf, acc_irf, ci, varnames, line_plot, acf_plot, rA, rB, rD)
}

